server:
  port : 8081  
    
spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: 
    driverClassName: com.mysql.cj.jdbc.NonRegisteringDriver

    