spring:
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://sql10.freemysqlhosting.net:5432/sql10358515
    username: sql10358515
    password: lCJ7H7Pppm
    driverClassName: com.mysql.cj.jdbc.NonRegisteringDriver

